test:
    host: localhost
    port: 5432
    user: postgres
    dbname: test
    sslmode: disable
    statementTimeout: "1s"
    workers: 5
    labels:
        production: "false"
    queryFiles:
        - "basic.yaml"
        - "pgsettings.yaml"
