odyssey_stats:
    query: "show stats"
    metrics:
        - database:
            usage: "LABEL"
            description: "Database name"
        - total_xact_count:
            usage: "COUNTER"
            description: "Total number of SQL transactions pooled by pgbouncer"
        - total_query_count:
            usage: "COUNTER"
            description: "Total number of SQL queries pooled by pgbouncer"
        - total_received:
            usage: "COUNTER"
            description: "Total volume in bytes of network traffic received by pgbouncer"
        - total_sent:
            usage: "COUNTER"
            description: "Total volume in bytes of network traffic sent by pgbouncer"
        - total_xact_time:
            usage: "COUNTER"
            description: "Total number of microseconds spent by pgbouncer when connected to PostgreSQL in a transaction, either idle in transaction or executing queries"
        - total_query_time:
            usage: "COUNTER"
            description: "Total number of microseconds spent by pgbouncer when actively connected to PostgreSQL, executing queries"
        - total_wait_time:
            usage: "COUNTER"
            description: "Time spent by clients waiting for a server in microseconds"
        - avg_xact_count:
            usage: "GAUGE"
            description: "Average transactions per second in last stat period"
        - avg_query_count:
            usage: "GAUGE"
            description: "Average queries per second in last stat period"
        - avg_recv:
            usage: "GAUGE"
            description: "Average received (from clients) bytes per second"
        - avg_sent:
            usage: "GAUGE"
            description: "Average sent (to clients) bytes per second"
        - avg_xact_time:
            usage: "GAUGE"
            description: "Average transaction duration in microseconds"
        - avg_query_time:
            usage: "GAUGE"
            description: "Average query duration in microseconds"
        - avg_wait_time:
            usage: "GAUGE"
            description: "Time spent by clients waiting for a server in microseconds (average per second)"

odyssey_lists:
    query: "show lists"
    nameColumn: "list"
    valueColumn: "items"
    metrics:
        - databases:
            usage: "GAUGE"
            description: "Databases"
        - users:
            usage: "GAUGE"
            description: "Users"
        - pools:
            usage: "GAUGE"
            description: "Pools"
        - free_clients:
            usage: "GAUGE"
            description: "Free clients"
        - used_clients:
            usage: "GAUGE"
            description: "Used clients"
        - login_clients:
            usage: "GAUGE"
            description: "Login clients"
        - free_servers:
            usage: "GAUGE"
            description: "Free servers"
        - used_servers:
            usage: "GAUGE"
            description: "Used servers"
        - dns_names:
            usage: "GAUGE"
            description: "DNS names"
        - dns_zones:
            usage: "GAUGE"
            description: "DNS zones"
        - dns_queries:
            usage: "GAUGE"
            description: "DNS queries"
        - dns_pending:
            usage: "GAUGE"
            description: "DNS pending"
