# sample query file

pgbouncer_stats:
    query: "show stats"
    metrics:
        - database:
            usage: "LABEL"
            description: "Database name"
        - total_xact_count:
            usage: "COUNTER"
            description: "Total number of SQL transactions pooled by pgbouncer"
        - total_query_count:
            usage: "COUNTER"
            description: "Total number of SQL queries pooled by pgbouncer"
        - total_received:
            usage: "COUNTER"
            description: "Total volume in bytes of network traffic received by pgbouncer"
        - total_sent:
            usage: "COUNTER"
            description: "Total volume in bytes of network traffic sent by pgbouncer"
        - total_xact_time:
            usage: "COUNTER"
            description: "Total number of microseconds spent by pgbouncer when connected to PostgreSQL in a transaction, either idle in transaction or executing queries"
        - total_query_time:
            usage: "COUNTER"
            description: "Total number of microseconds spent by pgbouncer when actively connected to PostgreSQL, executing queries"
        - total_wait_time:
            usage: "COUNTER"
            description: "Time spent by clients waiting for a server in microseconds"
        - avg_xact_count:
            usage: "GAUGE"
            description: "Average transactions per second in last stat period"
        - avg_query_count:
            usage: "GAUGE"
            description: "Average queries per second in last stat period"
        - avg_recv:
            usage: "GAUGE"
            description: "Average received (from clients) bytes per second"
        - avg_sent:
            usage: "GAUGE"
            description: "Average sent (to clients) bytes per second"
        - avg_xact_time:
            usage: "GAUGE"
            description: "Average transaction duration in microseconds"
        - avg_query_time:
            usage: "GAUGE"
            description: "Average query duration in microseconds"
        - avg_wait_time:
            usage: "GAUGE"
            description: "Time spent by clients waiting for a server in microseconds (average per second)"

pgbouncer_databases:
    query: "show databases"
    metrics:
        - name:
            usage: "LABEL"
            description: "Name of configured database entry."
        - host:
            usage: "LABEL"
            description: "Host pgbouncer connects to."
        - port:
            usage: "LABEL"
            description: "Port pgbouncer connects to."
        - database:
            usage: "LABEL"
            description: "Actual database name pgbouncer connects to."
        - force_user:
            usage: "LABEL"
            description: "When user is part of the connection string, the connection between pgbouncer and PostgreSQL is forced to the given user, whatever the client user."
        - pool_size:
            usage: "GAUGE"
            description: "Maximum number of server connections."
        - reserve_pool:
            usage: "GAUGE"
            description: "How many additional connections to allow to a pool. 0 disables."
        - pool_mode:
            usage: "LABEL"
            description: "The database's override pool_mode"
        - max_connections:
            usage: "GAUGE"
            description: "The database's override max_connections"
        - current_connections:
            usage: "GAUGE"
            description: "Total connections for this database in all pools"

pgbouncer_pools:
    query: "show pools"
    metrics:
        - database:
            usage: "LABEL"
            description: "Database name pgbouncer connects to."
        - user:
            usage: "LABEL"
            description: "User name"
        - cl_active:
            usage: "GAUGE"
            description: "Client connections that are linked to server connection and can process queries."
        - cl_waiting:
            usage: "GAUGE"
            description: "Client connections have sent queries but have not yet got a server connection."
        - sv_active:
            usage: "GAUGE"
            description: "Server connections that linked to client."
        - sv_idle:
            usage: "GAUGE"
            description: "Server connections that unused and immediately usable for client queries."
        - sv_used:
            usage: "GAUGE"
            description: "Server connections that have been idle more than server_check_delay, so they needs server_check_query to run on it before it can be used."
        - sv_tested:
            usage: "GAUGE"
            description: "Server connections that are currently running either server_reset_query or server_check_query."
        - sv_login:
            usage: "GAUGE"
            description: "Server connections currently in logging in process."
        - maxwait:
            usage: "GAUGE"
            description: "How long the first (oldest) client in queue has waited, in seconds."
        - pool_mode:
            usage: "LABEL"
            description: "The database’s override pool_mode"

pgbouncer_lists:
    query: "show lists"
    metrics:
        - databases:
            usage: "GAUGE"
            description: "Number of databases"
        - users:
            usage: "GAUGE"
            description: "Number of users"
        - pools:
            usage: "GAUGE"
            description: "Number of pools"
        - free_clients:
            usage: "GAUGE"
            description: "Number of free clients"
        - used_clients:
            usage: "GAUGE"
            description: "Number of used clients"
        - login_clients:
            usage: "GAUGE"
            description: "Number of clients in login state"
        - free_servers:
            usage: "GAUGE"
            description: "Number of free servers"
        - used_servers:
            usage: "GAUGE"
            description: "Number of used servers"
        - dns_names:
            usage: "GAUGE"
            description: "dns names"
        - dns_zones:
            usage: "GAUGE"
            description: "dns zones"
        - dns_queries:
            usage: "GAUGE"
            description: "dns queries"
        - dns_pending:
            usage: "GAUGE"
            description: "dns pending"

pgbouncer_mem:
    query: "show mem"
    metrics:
        - name:
            usage: "LABEL"
            description: "mem name"
        - size:
            usage: "GAUGE"
            description: "mem size"
        - used:
            usage: "GAUGE"
            description: "mem used"
        - free:
            usage: "GAUGE"
            description: "mem free"
        - memtotal:
            usage: "GAUGE"
            description: "mem total"